#!/bib/bash

# Create QR codes from a URL
# Usage: qrurl http://www.glad-conseil.com

qrurl()
{
    curl -sS "http://chart.apis.google.com/chart?chs=200x200&cht=qr&chld=H|0&chl=$1" -o - | display -filter point -resize 600x600 png:-;
}
