#!/bin/bash

# vim: ai ts=2 sw=2 et sts=2


# LOCALES =====================================================================

# Prefer FR French and use UTF-8
export LANG="fr_FR"
export LC_ALL="fr_FR.UTF-8"

# BRACKETS ====================================================================

bo="["
bc="]"
po="("
pc=")"
sp="─"
#export sp="───"

# VARIABLES ===================================================================

export AROBAS=${RESET}
export USER=${GREEN}
export SSH_IP=`echo $SSH_CLIENT | awk '{ print $1 }'`
export OS="$(uname -sr|awk '$1=="SunOS"&&$2>5{print"Solaris";exit};{print$1}')"
export BASEHOSTNAME="`echo "$HOSTNAME" | cut -d. -f1`";

if [ -d ~/tmp ]; then
    export TMPDIR=~/tmp
else
    mkdir ~/tmp 2>/dev/null
fi

# EDITOR ======================================================================

# Check for the presence of 'vim'.
VIMPATH=$(type -path vim 2>/dev/null);
if [ $? -eq 0 ]; then HAVE_VIM=yes; else unset -v HAVE_VIM; fi

if [ "$HAVE_VIM" ]; then
  function vi { $VIMPATH -O "$@"; }
  function vim { $VIMPATH -O "$@"; }
  EDITOR=vim;
else
  EDITOR=vi;
fi

export EDITOR;

# PAGER =======================================================================

if type -p most >/dev/null 2>&1; then
    PAGER='most -s'
elif type -p less >/dev/null 2>&1; then
    function pager() { less "$@"; }
    function more()  { less "$@"; }
    PAGER=less;
else
    function pager() { more "$@"; }
    PAGER=more;
fi

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# ignore case, long prompt, exit if it fits on one screen, allow colors for ls and grep colors
export LESS="-iMFXR"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"


# HISTORY =====================================================================

# Larger bash history (allow 32³ entries; default is 500)
# export HISTSIZE=32768
# Unlimited history
export HISTSIZE=
export HISTFILESIZE=$HISTSIZE
export HISTTIMEFORMAT="${RESET}${bo}${CDH}%d/%m/%Y${RESET}${bc} ${bo}${CHH}%H:%M:%S${RESET}${bc} "
export HISTCONTROL=ignorespace:erasedups
export HISTIGNORE="&:[bf]g:ls:cd:u:ll:l:la:l.:su:sbb:s:q:* --help"
# allow ctrl-S for history navigation (with ctrl-R)
stty -ixon

# GREP ========================================================================

# http://blog.amit-agarwal.co.in/2011/03/06/grep_colors-change-the-colors-in-the-grep-output/

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# one can set GREP_OPTIONS to "--color=auto --binary-files=without-match --line-number --ignore-case"
case "$TERM" in
    linux|xterm*)
        export GREP_COLOR='01;32'
        ;;
    *)
        export GREP_COLOR='(01);(38;5;46)'
        ;;
esac

# GIT ========================================================================

export GIT_PS1_SHOWDIRTYSTATE=1 GIT_PS1_SHOWUNTRACKEDFILES=1 GIT_PS1_SHOWSTASHSTATE=1


# MISC ========================================================================

# Export PhantomJS bin's location
#export PHANTOMJS_BIN="$(brew --prefix)/bin/phantomjs"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Make sure pkg-config can find self-compiled software
# and libraries (installed to ~/usr)
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:~/usr/lib/pkgconfig
export PKG_CONFIG_PATH

# Add custom compiled libraries to library search path.
# You must run the following command to activate path: ldconfig
# Verify Your New Library Path: ldconfig -v | less
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/local/lib
export LD_LIBRARY_PATH
 
# Add custom compiled libraries to library run path.
LD_RUN_PATH=$LD_RUN_PATH:~/local/lib
export LD_RUN_PATH
 
# Add custom Python modules to the Python path.
PYTHONPATH=$PYTHONPATH:~/slippenspythonlib
PYTHONPATH=$PYTHONPATH:~/usr/lib/python2.5/site-packages
export PYTHONPATH

# Java;s CLASSPATH customization
CLASSPATH=$CLASSPATH:~/foo/bar.jar
export CLASSPATH
